#!/usr/bin/env bash
# test-scaffold — Generate test stubs from a feature entry
set -euo pipefail
FEAT_ID="${1:-}"
FEATURES=".agent/FEATURES.md"

[[ -z "$FEAT_ID" ]] && echo "Usage: test-scaffold.sh FEAT-001" && exit 1
[[ ! -f "$FEATURES" ]] && echo "No FEATURES.md found" && exit 1

# Extract feature name and criteria
FEAT_NAME=$(grep -A1 "## \[$FEAT_ID\]" "$FEATURES" 2>/dev/null | head -1 | sed "s/## \[$FEAT_ID\] //")
[[ -z "$FEAT_NAME" ]] && echo "Feature $FEAT_ID not found in FEATURES.md" && exit 1

# Generate test file path
SLUG=$(echo "$FEAT_NAME" | tr '[:upper:]' '[:lower:]' | tr ' ' '-' | tr -cd '[:alnum:]-')
TEST_DIR="tests/unit"
mkdir -p "$TEST_DIR"
TEST_FILE="$TEST_DIR/$SLUG.test.ts"

# Extract acceptance criteria
CRITERIA=$(grep -A50 "## \[$FEAT_ID\]" "$FEATURES" | grep "^- \[ \]" | sed 's/- \[ \] //')

# Generate test stubs
cat > "$TEST_FILE" << TESTEOF
/**
 * Tests for [$FEAT_ID] $FEAT_NAME
 * Generated by test-scaffold.sh
 * Status: STUBS — implement before marking feature complete
 */

describe('[$FEAT_ID] $FEAT_NAME', () => {
  beforeEach(() => {
    // TODO: setup
  });

  afterEach(() => {
    // TODO: teardown
  });

TESTEOF

while IFS= read -r criterion; do
  [[ -z "$criterion" ]] && continue
  cat >> "$TEST_FILE" << CRITEOF
  // Acceptance criterion: $criterion
  it('should $(echo "$criterion" | tr '[:upper:]' '[:lower:]')', () => {
    // TODO: implement test
    expect(true).toBe(false); // force fail until implemented
  });

CRITEOF
done <<< "$CRITERIA"

echo "});" >> "$TEST_FILE"

echo "✓ Test stubs written to $TEST_FILE"
echo "  $FEAT_ID has $(echo "$CRITERIA" | grep -c . || echo 0) test(s) to implement."
echo "  Tests will FAIL until implemented — this is correct."
