#!/usr/bin/env bash
# test-scaffold — Generate test stubs from a feature entry
set -euo pipefail
FEAT_ID="${1:-}"
FEATURES=".agent/FEATURES.md"

[[ -z "$FEAT_ID" ]] && echo "Usage: test-scaffold.sh FEAT-001" && exit 1
[[ ! -f "$FEATURES" ]] && echo "No FEATURES.md found" && exit 1

# Isolate exactly this feature's block: from its own "### [FEAT-ID]" header
# up to (but not including) the next "### [FEAT-" header, or EOF. Using a
# fixed line-count window here previously bled into the next feature's
# acceptance criteria for short entries.
BLOCK=$(awk -v id="$FEAT_ID" '
  $0 ~ "^### \\[" id "\\]" { found=1; print; next }
  found && /^### \[FEAT-/ { exit }
  found { print }
' "$FEATURES")

[[ -z "$BLOCK" ]] && echo "Feature $FEAT_ID not found in FEATURES.md" && exit 1

FEAT_NAME=$(echo "$BLOCK" | head -1 | sed -E "s/^### \[$FEAT_ID\] //")

# Find the test file path declared under this feature's **Tests:** section
# (first backtick path on the line(s) following **Tests:**, before the next
# **Section:**). Falls back to a generic tests/unit/<slug>.test.ts if the
# feature doesn't declare one.
TEST_FILE=$(echo "$BLOCK" | awk '
  /^\*\*Tests:\*\*/ { intests=1; next }
  intests && /^\*\*/ { exit }
  intests { print }
' | grep -o '`[^`]*`' | head -1 | tr -d '`')

SLUG=$(echo "$FEAT_NAME" | tr '[:upper:]' '[:lower:]' | tr ' ' '-' | tr -cd '[:alnum:]-')

if [[ -z "$TEST_FILE" ]]; then
  TEST_FILE="tests/unit/$SLUG.test.ts"
fi

TEST_DIR=$(dirname "$TEST_FILE")
mkdir -p "$TEST_DIR"

# Acceptance criteria — only from this feature's own bounded block.
CRITERIA=$(echo "$BLOCK" | grep "^- \[ \]" | sed 's/- \[ \] //')

if [[ -f "$TEST_FILE" ]]; then
  echo "⚠ $TEST_FILE already exists — not overwriting. Delete it first if you want fresh stubs."
  exit 1
fi

case "$TEST_FILE" in
  *.py)
    # pytest stubs
    {
      echo "# Tests for [$FEAT_ID] $FEAT_NAME"
      echo "# Generated by test-scaffold.sh"
      echo "# Status: STUBS — implement before marking feature complete"
      echo ""
      echo "import pytest"
      echo ""
      echo ""
      while IFS= read -r criterion; do
        [[ -z "$criterion" ]] && continue
        fn_name=$(echo "$criterion" | tr '[:upper:]' '[:lower:]' | tr -cs '[:alnum:]' '_' | sed 's/^_*//;s/_*$//' | cut -c1-60)
        echo "# Acceptance criterion: $criterion"
        echo "def test_${fn_name}():"
        echo "    # TODO: implement test"
        echo "    pytest.fail(\"not implemented\")"
        echo ""
      done <<< "$CRITERIA"
    } > "$TEST_FILE"
    ;;
  *)
    # vitest/jest stubs (default for .ts/.tsx/.js)
    {
      echo "/**"
      echo " * Tests for [$FEAT_ID] $FEAT_NAME"
      echo " * Generated by test-scaffold.sh"
      echo " * Status: STUBS — implement before marking feature complete"
      echo " */"
      echo ""
      echo "describe('[$FEAT_ID] $FEAT_NAME', () => {"
      echo "  beforeEach(() => {"
      echo "    // TODO: setup"
      echo "  });"
      echo ""
      echo "  afterEach(() => {"
      echo "    // TODO: teardown"
      echo "  });"
      echo ""
      while IFS= read -r criterion; do
        [[ -z "$criterion" ]] && continue
        echo "  // Acceptance criterion: $criterion"
        echo "  it('should $(echo "$criterion" | tr '[:upper:]' '[:lower:]')', () => {"
        echo "    // TODO: implement test"
        echo "    expect(true).toBe(false); // force fail until implemented"
        echo "  });"
        echo ""
      done <<< "$CRITERIA"
      echo "});"
    } > "$TEST_FILE"
    ;;
esac

echo "✓ Test stubs written to $TEST_FILE"
echo "  $FEAT_ID has $(echo "$CRITERIA" | grep -c . || echo 0) test(s) to implement."
echo "  Tests will FAIL until implemented — this is correct."
